version: '3.5'
services:
  scrape:
      build: scrape
      container_name: scrape
      volumes:
          - ./scrape:/home/scrape
      command: /bin/bash 
      

  grobid:
    image: lfoppiano/grobid:0.7.2
    container_name: grobid
    ports:
      - 8080:8070
      - 8081:8071